# Generated by Django 4.2.2 on 2023-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postagem_Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("texto", models.TextField()),
                ("data_postagem", models.DateField()),
                ("imagem", models.ImageField(upload_to="static/img")),
            ],
        ),
    ]
