# Generated by Django 4.2.2 on 2023-06-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postagem_Alimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("texto", models.TextField()),
                ("data_postagem", models.DateField()),
                ("imagem", models.ImageField(upload_to="static/img")),
            ],
        ),
        migrations.CreateModel(
            name="Postagem_Apicultura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("texto", models.TextField()),
                ("data_postagem", models.DateField()),
                ("imagem", models.ImageField(upload_to="static/img")),
            ],
        ),
        migrations.RenameModel(
            old_name="Postagem_Curso",
            new_name="Postagem_Informatica",
        ),
    ]
